services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - APP_ENV=production
    volumes:
      - .:/app
